// Tourist VAT / GST Refund data — 2024 rates
// netRefundFraction = fraction of embedded VAT you actually receive after processing fees
// embeddedVAT = purchaseAmount × vatRate / (1 + vatRate)
// estimatedRefund = embeddedVAT × netRefundFraction

export const VAT_REGIONS = {
  Europe:        ['DE','FR','IT','ES','NL','CH','AT','BE','SE','NO','DK','FI','PT','IE','GR','PL','CZ','HU','RO','SK','HR','SI','LU','MT','LV','LT','EE','BG','IS','TR','GB'],
  'Asia Pacific':['AU','JP','KR','SG','TW','TH','MY'],
  'Middle East': ['AE','SA','QA','BH'],
  Americas:      ['AR','US','CA','MX'],
  'No Refund':   ['CN','IN','ID','PH','VN','NZ','BR'],
};

export const VAT_COUNTRIES = {
  // ── Europe ──────────────────────────────────────────────────────────────
  DE: {
    name: 'Germany', flag: '🇩🇪', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.19, vatName: 'VAT (MwSt)',
    minPurchase: 50, netRefundFraction: 0.74,
    operator: 'Global Blue / Planet',
    claimAt: 'Airport PABLO kiosk or customs desk before departure',
    steps: ['Get tax-free form from retailer','Have goods ready + passport','Stamp form at airport customs','Get refund at cash desk or card'],
    note: 'Goods must be unused and exported within 3 months. Purchase from one retailer in one day.',
  },
  FR: {
    name: 'France', flag: '🇫🇷', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.20, vatName: 'VAT (TVA)',
    minPurchase: 100, netRefundFraction: 0.78,
    operator: 'Global Blue / PABLO',
    claimAt: 'PABLO kiosk at CDG, ORY, or NCE — scan barcode on form',
    steps: ['Ask retailer for détaxe form (≥€100 in one shop)','Keep goods in cabin baggage','Validate at PABLO kiosk before check-in','Refund credited to card (10–30 days) or cash at counter'],
    note: 'PABLO is the fastest — scans form, no customs officer needed. Must not be EU resident.',
  },
  IT: {
    name: 'Italy', flag: '🇮🇹', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.22, vatName: 'VAT (IVA)',
    minPurchase: 155, netRefundFraction: 0.72,
    operator: 'Global Blue / Planet',
    claimAt: 'Customs office at departure airport',
    steps: ['Spend ≥€154.94 in one store','Get tax-free invoice','Customs stamp at airport','Cash or card refund at refund desk'],
    note: 'Minimum is €154.94 (increased from €155 threshold). Luxury goods popular in Italy.',
  },
  ES: {
    name: 'Spain', flag: '🇪🇸', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.21, vatName: 'VAT (IVA)',
    minPurchase: 91, netRefundFraction: 0.74,
    operator: 'Global Blue / Planet',
    claimAt: 'Customs at departure airport or DIVA kiosk',
    steps: ['Purchase ≥€90.16 at participating shop','Get tax-free form','Validate at DIVA kiosk or customs counter','Collect refund at Planet/Global Blue desk'],
    note: 'DIVA electronic validation available at major airports (MAD, BCN).',
  },
  NL: {
    name: 'Netherlands', flag: '🇳🇱', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.21, vatName: 'VAT (BTW)',
    minPurchase: 50, netRefundFraction: 0.73,
    operator: 'Global Blue / Planet',
    claimAt: 'Schiphol Airport — Tax Refund desk',
    steps: ['Ask for tax-free form at retailer','Present passport','Customs stamp before check-in','Refund at Planet desk in Schiphol'],
    note: 'Non-EU residents only. Goods must leave EU within 90 days.',
  },
  CH: {
    name: 'Switzerland', flag: '🇨🇭', region: 'Europe',
    hasRefund: true, currency: 'CHF', symbol: 'CHF ',
    vatRate: 0.081, vatName: 'VAT (MWST)',
    minPurchase: 300, netRefundFraction: 0.60,
    operator: 'Global Blue',
    claimAt: 'Swiss customs at airport before departing',
    steps: ['Spend ≥CHF 300 in one day at one store','Get Global Blue form','Swiss customs stamp at departure','Refund at Global Blue desk or credited to card'],
    note: 'Switzerland has a lower VAT rate but higher processing fees. Non-Swiss residents only.',
  },
  AT: {
    name: 'Austria', flag: '🇦🇹', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.20, vatName: 'VAT (MwSt)',
    minPurchase: 75, netRefundFraction: 0.74,
    operator: 'Global Blue / Planet',
    claimAt: 'Vienna International Airport — customs',
    steps: ['Spend ≥€75 in one retailer','Get tax-free cheque','Customs validation at airport','Cash or card refund'],
    note: 'Standard 20% VAT. Non-EU residents only.',
  },
  BE: {
    name: 'Belgium', flag: '🇧🇪', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.21, vatName: 'VAT (BTW/TVA)',
    minPurchase: 125, netRefundFraction: 0.73,
    operator: 'Global Blue / Planet',
    claimAt: 'Brussels Airport — customs desk',
    steps: ['Spend ≥€125.01 in one store','Collect tax-free form','Customs stamp at Brussels Airport','Refund at operator desk'],
    note: 'Highest minimum in EU. Non-EU residents only.',
  },
  SE: {
    name: 'Sweden', flag: '🇸🇪', region: 'Europe',
    hasRefund: true, currency: 'SEK', symbol: 'kr ',
    vatRate: 0.25, vatName: 'VAT (MOMS)',
    minPurchase: 200, netRefundFraction: 0.75,
    operator: 'Global Blue',
    claimAt: 'Stockholm Arlanda or departure airport',
    steps: ['Shop at tax-free retailer (≥SEK 200)','Show passport','Get Global Blue cheque','Redeem at airport'],
    note: 'One of the highest VAT rates in Europe (25%).',
  },
  NO: {
    name: 'Norway', flag: '🇳🇴', region: 'Europe',
    hasRefund: true, currency: 'NOK', symbol: 'kr ',
    vatRate: 0.25, vatName: 'VAT (MVA)',
    minPurchase: 315, netRefundFraction: 0.75,
    operator: 'Global Blue',
    claimAt: 'Oslo Gardermoen Airport',
    steps: ['Purchase ≥NOK 315 in one day at one shop','Get tax-free form','Customs stamp at airport','Refund at desk'],
    note: 'Norway is not in EU but has its own refund scheme.',
  },
  DK: {
    name: 'Denmark', flag: '🇩🇰', region: 'Europe',
    hasRefund: true, currency: 'DKK', symbol: 'kr ',
    vatRate: 0.25, vatName: 'VAT (MOMS)',
    minPurchase: 300, netRefundFraction: 0.74,
    operator: 'Global Blue / Planet',
    claimAt: 'Copenhagen Airport (CPH)',
    steps: ['Shop ≥DKK 300 in one store','Receive tax-free form','Customs at CPH','Refund desk'],
    note: 'Includes Greenland and Faroe Islands purchases? No — DK mainland only.',
  },
  FI: {
    name: 'Finland', flag: '🇫🇮', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.255, vatName: 'VAT (ALV)',
    minPurchase: 40, netRefundFraction: 0.74,
    operator: 'Global Blue',
    claimAt: 'Helsinki-Vantaa Airport',
    steps: ['Purchase ≥€40 in one retailer','Get tax-free form with passport','Customs stamp','Refund at Global Blue desk'],
    note: 'Lowest minimum threshold in EU at just €40.',
  },
  PT: {
    name: 'Portugal', flag: '🇵🇹', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.23, vatName: 'VAT (IVA)',
    minPurchase: 62, netRefundFraction: 0.73,
    operator: 'Global Blue / Planet',
    claimAt: 'Lisbon (LIS) or Porto (OPO) Airport',
    steps: ['Spend ≥€61.35 in one shop','Get tax-free form','Customs before check-in','Refund at operator desk'],
    note: 'Includes Madeira and Azores. Non-EU only.',
  },
  IE: {
    name: 'Ireland', flag: '🇮🇪', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.23, vatName: 'VAT',
    minPurchase: 30, netRefundFraction: 0.73,
    operator: 'Premier Tax Free (Planet)',
    claimAt: 'Dublin Airport — customs',
    steps: ['Spend ≥€30 in one store','Show passport, get tax-free form','Customs stamp at Dublin Airport','Refund at desk or by post'],
    note: 'Lowest minimum in EU at €30. Non-EU residents only.',
  },
  GR: {
    name: 'Greece', flag: '🇬🇷', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.24, vatName: 'VAT (ΦΠΑ)',
    minPurchase: 50, netRefundFraction: 0.72,
    operator: 'Global Blue',
    claimAt: 'Athens (ATH) or Thessaloniki (SKG) Airport',
    steps: ['Purchase ≥€50 in one retailer','Get tax-free form','Customs at airport','Refund at desk'],
    note: 'Non-EU tourists only. Goods must leave within 3 months.',
  },
  PL: {
    name: 'Poland', flag: '🇵🇱', region: 'Europe',
    hasRefund: true, currency: 'PLN', symbol: 'zł ',
    vatRate: 0.23, vatName: 'VAT (PTU)',
    minPurchase: 200, netRefundFraction: 0.73,
    operator: 'Global Blue',
    claimAt: 'Warsaw Chopin (WAW) or Kraków (KRK) Airport',
    steps: ['Spend ≥PLN 200 in one retailer','Passport + tax-free form','Customs at airport','Refund at desk'],
    note: 'Non-EU residents only. Popular for amber and crystal goods.',
  },
  CZ: {
    name: 'Czech Republic', flag: '🇨🇿', region: 'Europe',
    hasRefund: true, currency: 'CZK', symbol: 'Kč ',
    vatRate: 0.21, vatName: 'VAT (DPH)',
    minPurchase: 2001, netRefundFraction: 0.73,
    operator: 'Global Blue',
    claimAt: 'Prague (PRG) Airport',
    steps: ['Spend ≥CZK 2,001 in one retailer','Get tax-free form','Customs at PRG','Refund at desk'],
    note: 'Non-EU residents only.',
  },
  HU: {
    name: 'Hungary', flag: '🇭🇺', region: 'Europe',
    hasRefund: true, currency: 'HUF', symbol: 'Ft ',
    vatRate: 0.27, vatName: 'VAT (ÁFA)',
    minPurchase: 54001, netRefundFraction: 0.72,
    operator: 'Global Blue',
    claimAt: 'Budapest (BUD) Airport',
    steps: ['Purchase ≥HUF 54,001 in one retailer','Tax-free form + passport','Customs at airport','Refund at desk'],
    note: 'Highest VAT rate in the EU at 27%.',
  },
  RO: {
    name: 'Romania', flag: '🇷🇴', region: 'Europe',
    hasRefund: true, currency: 'RON', symbol: 'lei ',
    vatRate: 0.19, vatName: 'VAT (TVA)',
    minPurchase: 250, netRefundFraction: 0.72,
    operator: 'Global Blue',
    claimAt: 'Bucharest (OTP) Airport',
    steps: ['Spend ≥RON 250 in one retailer','Tax-free form','Customs validation','Refund at desk'],
    note: 'Non-EU residents only.',
  },
  SK: {
    name: 'Slovakia', flag: '🇸🇰', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.20, vatName: 'VAT (DPH)',
    minPurchase: 175, netRefundFraction: 0.72,
    operator: 'Global Blue',
    claimAt: 'Bratislava (BTS) Airport',
    steps: ['Purchase ≥€175 in one retailer','Tax-free form','Customs at airport','Refund at desk'],
    note: 'Non-EU residents only.',
  },
  HR: {
    name: 'Croatia', flag: '🇭🇷', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.25, vatName: 'VAT (PDV)',
    minPurchase: 100, netRefundFraction: 0.73,
    operator: 'Global Blue',
    claimAt: 'Zagreb (ZAG) Airport or border crossing',
    steps: ['Spend ≥€100 in one retailer','Tax-free form','Customs at exit from Croatia','Refund at desk'],
    note: 'Croatia joined EU (and Euro) in 2023. Non-EU tourists only.',
  },
  IS: {
    name: 'Iceland', flag: '🇮🇸', region: 'Europe',
    hasRefund: true, currency: 'ISK', symbol: 'kr ',
    vatRate: 0.24, vatName: 'VAT (VSK)',
    minPurchase: 6000, netRefundFraction: 0.75,
    operator: 'Iceland Tax Free',
    claimAt: 'Keflavik International Airport (KEF)',
    steps: ['Purchase ≥ISK 6,000 in one store','Iceland Tax Free form','Customs at KEF','Refund at desk'],
    note: 'Iceland is not in EU. Non-Icelandic residents. Popular for wool goods.',
  },
  TR: {
    name: 'Turkey', flag: '🇹🇷', region: 'Europe',
    hasRefund: true, currency: 'TRY', symbol: '₺',
    vatRate: 0.20, vatName: 'VAT (KDV)',
    minPurchase: 100, netRefundFraction: 0.70,
    operator: 'Global Blue / Denizbank',
    claimAt: 'Airport customs before check-in',
    steps: ['Purchase ≥TRY 100 in one retailer','Show passport, get tax-free invoice','Customs stamp at airport','Refund at bank desk or via card'],
    note: 'Non-Turkish residents only. Common for leather, textiles, and ceramics.',
  },
  GB: {
    name: 'United Kingdom', flag: '🇬🇧', region: 'Europe',
    hasRefund: false,
    currency: 'GBP', symbol: '£', vatRate: 0.20, vatName: 'VAT',
    noRefundReason: 'The UK ended its tax-free shopping scheme for overseas visitors in January 2021 following Brexit. A new scheme was under consultation but not yet implemented as of 2024. Some airside duty-free shopping is available.',
  },
  LU: {
    name: 'Luxembourg', flag: '🇱🇺', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.17, vatName: 'VAT (TVA)',
    minPurchase: 74, netRefundFraction: 0.74,
    operator: 'Global Blue',
    claimAt: 'Luxembourg Airport (LUX)',
    steps: ['Purchase ≥€74 in one retailer','Tax-free form','Customs','Refund'],
    note: 'Lowest standard VAT rate in EU at 17%.',
  },
  MT: {
    name: 'Malta', flag: '🇲🇹', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.18, vatName: 'VAT',
    minPurchase: 100, netRefundFraction: 0.73,
    operator: 'Global Blue',
    claimAt: 'Malta International Airport (MLA)',
    steps: ['Spend ≥€100 in one retailer','Tax-free form','Customs at MLA','Refund at desk'],
    note: 'Non-EU residents only.',
  },
  LV: {
    name: 'Latvia', flag: '🇱🇻', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.21, vatName: 'VAT (PVN)',
    minPurchase: 44, netRefundFraction: 0.73,
    operator: 'Global Blue',
    claimAt: 'Riga (RIX) Airport',
    steps: ['Spend ≥€44 in one store','Tax-free form','Customs at RIX','Refund'],
    note: 'Non-EU residents only.',
  },
  LT: {
    name: 'Lithuania', flag: '🇱🇹', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.21, vatName: 'VAT (PVM)',
    minPurchase: 26, netRefundFraction: 0.73,
    operator: 'Global Blue',
    claimAt: 'Vilnius (VNO) Airport',
    steps: ['Spend ≥€26 in one retailer','Tax-free form','Customs at VNO','Refund'],
    note: 'Second-lowest minimum in EU after Ireland.',
  },
  EE: {
    name: 'Estonia', flag: '🇪🇪', region: 'Europe',
    hasRefund: true, currency: 'EUR', symbol: '€',
    vatRate: 0.22, vatName: 'VAT (KM)',
    minPurchase: 38, netRefundFraction: 0.73,
    operator: 'Global Blue',
    claimAt: 'Tallinn Airport (TLL)',
    steps: ['Purchase ≥€38 in one retailer','Tax-free form','Customs','Refund'],
    note: 'Non-EU residents only.',
  },
  BG: {
    name: 'Bulgaria', flag: '🇧🇬', region: 'Europe',
    hasRefund: true, currency: 'BGN', symbol: 'лв ',
    vatRate: 0.20, vatName: 'VAT (ДДС)',
    minPurchase: 250, netRefundFraction: 0.72,
    operator: 'Global Blue',
    claimAt: 'Sofia (SOF) Airport',
    steps: ['Spend ≥BGN 250 in one retailer','Tax-free form','Customs at SOF','Refund'],
    note: 'Non-EU residents only.',
  },

  // ── Asia Pacific ──────────────────────────────────────────────────────────
  AU: {
    name: 'Australia', flag: '🇦🇺', region: 'Asia Pacific',
    hasRefund: true, currency: 'AUD', symbol: 'A$',
    vatRate: 0.10, vatName: 'GST',
    minPurchase: 300, netRefundFraction: 1.0,
    operator: 'Tourist Refund Scheme (TRS) — Australian Border Force',
    claimAt: 'TRS kiosk at international departure terminal — no form needed',
    steps: ['Spend ≥A$300 (GST inc.) from single ABN in 60 days','Keep tax invoices','At airport, proceed through security to international terminal','Scan receipts at TRS kiosk — refund to card or PayPal'],
    note: 'Full GST refund — zero processing fee. Fastest and fairest tourist refund in the world.',
  },
  JP: {
    name: 'Japan', flag: '🇯🇵', region: 'Asia Pacific',
    hasRefund: true, currency: 'JPY', symbol: '¥',
    vatRate: 0.10, vatName: 'Consumption Tax',
    minPurchase: 5001, netRefundFraction: 0.92,
    operator: 'In-store Tax-Free (Kansen / Menzei)',
    claimAt: 'Usually in-store at point of sale — no airport claim needed',
    steps: ['Shop at stores displaying "Tax-Free" sign','Spend ≥¥5,001 general goods (¥5,001 consumables separately)','Show passport at checkout','Tax deducted immediately — goods sealed until departure'],
    note: 'Tax removed at checkout — you pay the net price directly. Goods must be exported. Consumables (cosmetics, food) must stay sealed in tamper-evident bag.',
  },
  KR: {
    name: 'South Korea', flag: '🇰🇷', region: 'Asia Pacific',
    hasRefund: true, currency: 'KRW', symbol: '₩',
    vatRate: 0.10, vatName: 'VAT',
    minPurchase: 30000, netRefundFraction: 0.85,
    operator: 'Global Blue / KT&G / in-store',
    claimAt: 'Airport refund desk at ICN/GMP or in-store (same-day)',
    steps: ['Spend ≥₩30,000 (department stores ₩15,000) in one retailer','Get tax-free receipt','Customs stamp','Refund at airport desk or automated kiosk'],
    note: 'Duty-free shopping also available at Korean department stores. Popular for cosmetics and electronics.',
  },
  SG: {
    name: 'Singapore', flag: '🇸🇬', region: 'Asia Pacific',
    hasRefund: true, currency: 'SGD', symbol: 'S$',
    vatRate: 0.09, vatName: 'GST',
    minPurchase: 100, netRefundFraction: 0.88,
    operator: 'Global Blue / Changi Airport eTRS',
    claimAt: 'eTRS kiosk at Changi Airport — electronic self-service',
    steps: ['Spend ≥S$100 (GST inc.) in one retailer in one day','Request eTRS ticket at checkout (show passport)','At Changi Airport, use eTRS self-help kiosk','Approve refund — paid to card or collected as cash'],
    note: 'eTRS (Electronic Tourist Refund Scheme) is fast and paperless. Refund denied if goods already in checked-in bags.',
  },
  TW: {
    name: 'Taiwan', flag: '🇹🇼', region: 'Asia Pacific',
    hasRefund: true, currency: 'TWD', symbol: 'NT$',
    vatRate: 0.05, vatName: 'Business Tax (VAT)',
    minPurchase: 2000, netRefundFraction: 0.94,
    operator: 'Taiwan Tax Refund',
    claimAt: 'CKS/TPE Airport or harbour tax refund counter',
    steps: ['Purchase ≥NT$2,000 (VAT inc.) in one store in one day','Get uniform invoice + tax refund application','Customs stamp at airport','Refund at counter — cash or card'],
    note: 'Taiwan has a very low VAT rate (5%) but the refund is almost in full. Popular for electronics and night market goods.',
  },
  TH: {
    name: 'Thailand', flag: '🇹🇭', region: 'Asia Pacific',
    hasRefund: true, currency: 'THB', symbol: '฿',
    vatRate: 0.07, vatName: 'VAT',
    minPurchase: 2000, netRefundFraction: 0.82,
    operator: 'Revenue Department of Thailand',
    claimAt: 'VAT Refund for Tourists counter at international airports (BKK, HKT, etc.)',
    steps: ['Purchase ≥฿2,000 in one store on same day','Get VAT refund form (PP.10) stamped by retailer','Customs inspection before check-in','Refund at Revenue Dept counter'],
    note: 'Goods must be taken out of Thailand within 60 days. Cash refund has ฿100 fee. Over ฿30,000 — refund by cheque.',
  },
  MY: {
    name: 'Malaysia', flag: '🇲🇾', region: 'Asia Pacific',
    hasRefund: true, currency: 'MYR', symbol: 'RM ',
    vatRate: 0.10, vatName: 'Sales & Service Tax (SST)',
    minPurchase: 300, netRefundFraction: 0.75,
    operator: 'Malaysia Tourism Tax Refund',
    claimAt: 'KLIA / KLIA2 / Penang / Langkawi Airport',
    steps: ['Purchase ≥RM 300 (SST inc.) in one retailer','Get tax-free invoice from participating stores','Customs counter at departure','Refund at Tourism Malaysia desk'],
    note: 'Limited to participating stores. Check for "Tax Free Shopping" logo.',
  },

  // ── Middle East ──────────────────────────────────────────────────────────
  AE: {
    name: 'United Arab Emirates', flag: '🇦🇪', region: 'Middle East',
    hasRefund: true, currency: 'AED', symbol: 'AED ',
    vatRate: 0.05, vatName: 'VAT',
    minPurchase: 250, netRefundFraction: 0.85,
    operator: 'Planet (Official UAE Tax-Free Shopping)',
    claimAt: 'Dubai (DXB/DWC), Abu Dhabi (AUH), or Sharjah (SHJ) Airport kiosks',
    steps: ['Spend ≥AED 250 at registered retailer','Cashier captures your passport at checkout','At airport departure, use self-service kiosk','Approve refund — card or cash (cash has higher fee)'],
    note: 'Fully digital — no paper forms. UAE VAT (5%) is low but applies to most goods. Popular for gold and electronics.',
  },
  SA: {
    name: 'Saudi Arabia', flag: '🇸🇦', region: 'Middle East',
    hasRefund: true, currency: 'SAR', symbol: 'SAR ',
    vatRate: 0.15, vatName: 'VAT',
    minPurchase: 1000, netRefundFraction: 0.80,
    operator: 'Planet (limited rollout)',
    claimAt: 'Riyadh (RUH) or Jeddah (JED) Airport',
    steps: ['Purchase ≥SAR 1,000 at registered store','Get e-receipt from Planet system','Airport tax refund kiosk','Card refund'],
    note: 'Saudi Arabia launched tourist VAT refund in 2023. Still limited to registered stores in Riyadh and Jeddah.',
  },
  QA: {
    name: 'Qatar', flag: '🇶🇦', region: 'Middle East',
    hasRefund: true, currency: 'QAR', symbol: 'QAR ',
    vatRate: 0.00, vatName: 'No VAT',
    minPurchase: 0, netRefundFraction: 0,
    hasRefund: false,
    noRefundReason: 'Qatar has no VAT as of 2024 — prices are VAT-free already. However, the 2022 World Cup Tax Refund Scheme has ended.',
  },
  BH: {
    name: 'Bahrain', flag: '🇧🇭', region: 'Middle East',
    hasRefund: true, currency: 'BHD', symbol: 'BD ',
    vatRate: 0.10, vatName: 'VAT',
    minPurchase: 100, netRefundFraction: 0.78,
    operator: 'Planet / NBB',
    claimAt: 'Bahrain International Airport (BAH)',
    steps: ['Spend ≥BHD 100 at registered retailer','Get tax-free form','Customs at BAH','Refund at desk'],
    note: 'Bahrain introduced VAT in 2019. Tourist refund scheme is limited.',
  },

  // ── Americas ─────────────────────────────────────────────────────────────
  AR: {
    name: 'Argentina', flag: '🇦🇷', region: 'Americas',
    hasRefund: true, currency: 'ARS', symbol: '$',
    vatRate: 0.21, vatName: 'IVA',
    minPurchase: 70, netRefundFraction: 0.70,
    operator: 'Tax Free Argentina / Global Exchange',
    claimAt: 'Ezeiza (EZE) Airport or Aeroparque (AEP)',
    steps: ['Spend ≥ARS 70 per ticket at registered store','Get Global Exchange voucher','Customs at airport','Refund in USD or ARS at exchange desk'],
    note: 'Currency volatility affects value significantly. Refund often paid in USD at official rate.',
  },
  US: {
    name: 'United States', flag: '🇺🇸', region: 'Americas',
    hasRefund: false,
    currency: 'USD', symbol: '$', vatRate: 0, vatName: 'Sales Tax (no federal VAT)',
    noRefundReason: 'The USA has no federal VAT. Sales taxes are state-level and non-refundable to tourists. Louisiana (4.45%) offers a limited refund at participating stores for purchases over $500.',
  },
  CA: {
    name: 'Canada', flag: '🇨🇦', region: 'Americas',
    hasRefund: false,
    currency: 'CAD', symbol: 'C$', vatRate: 0.05, vatName: 'GST / HST',
    noRefundReason: 'Canada ended the Visitor Rebate Programme (VRP) in 2007. GST/HST is no longer refundable to visiting tourists.',
  },
  MX: {
    name: 'Mexico', flag: '🇲🇽', region: 'Americas',
    hasRefund: false,
    currency: 'MXN', symbol: 'MX$', vatRate: 0.16, vatName: 'IVA',
    noRefundReason: 'Mexico has no standard tourist VAT refund program. Some Cancún and border retailers offer informal refunds but there is no official national scheme.',
  },

  // ── No Refund Countries ──────────────────────────────────────────────────
  CN: {
    name: 'China', flag: '🇨🇳', region: 'No Refund',
    hasRefund: false,
    currency: 'CNY', symbol: '¥', vatRate: 0.13, vatName: 'VAT',
    noRefundReason: 'China does not have a standard tourist VAT refund program. A pilot scheme exists in Hainan Free Trade Port but is very limited.',
  },
  IN: {
    name: 'India', flag: '🇮🇳', region: 'No Refund',
    hasRefund: false,
    currency: 'INR', symbol: '₹', vatRate: 0.18, vatName: 'GST',
    noRefundReason: 'India has no tourist VAT/GST refund program.',
  },
  ID: {
    name: 'Indonesia', flag: '🇮🇩', region: 'No Refund',
    hasRefund: false,
    currency: 'IDR', symbol: 'Rp ', vatRate: 0.11, vatName: 'PPN (VAT)',
    noRefundReason: 'Indonesia has no tourist VAT refund scheme.',
  },
  PH: {
    name: 'Philippines', flag: '🇵🇭', region: 'No Refund',
    hasRefund: false,
    currency: 'PHP', symbol: '₱', vatRate: 0.12, vatName: 'VAT',
    noRefundReason: 'The Philippines has no tourist VAT refund program.',
  },
  VN: {
    name: 'Vietnam', flag: '🇻🇳', region: 'No Refund',
    hasRefund: false,
    currency: 'VND', symbol: '₫', vatRate: 0.10, vatName: 'VAT',
    noRefundReason: 'Vietnam has no tourist VAT refund program as of 2024.',
  },
  NZ: {
    name: 'New Zealand', flag: '🇳🇿', region: 'No Refund',
    hasRefund: false,
    currency: 'NZD', symbol: 'NZ$', vatRate: 0.15, vatName: 'GST',
    noRefundReason: 'New Zealand ended its Duty Free and Tourist Refund scheme. No GST refund for tourists.',
  },
  BR: {
    name: 'Brazil', flag: '🇧🇷', region: 'No Refund',
    hasRefund: false,
    currency: 'BRL', symbol: 'R$', vatRate: 0.17, vatName: 'ICMS (avg)',
    noRefundReason: 'Brazil has no nationwide tourist tax refund program. Manaus Free Trade Zone offers some incentives.',
  },
};

// ── Helper to get sorted country list by region ────────────────────────────
export function getVATCountryList() {
  const order = ['Europe','Asia Pacific','Middle East','Americas','No Refund'];
  const result = [];
  order.forEach(region => {
    const codes = VAT_REGIONS[region] || [];
    codes.forEach(code => {
      const c = VAT_COUNTRIES[code];
      if (c) result.push({ code, ...c, region });
    });
  });
  // Also include any countries not in regions
  Object.entries(VAT_COUNTRIES).forEach(([code, c]) => {
    if (!result.find(r => r.code === code)) result.push({ code, ...c });
  });
  return result;
}

// ── Calculate tourist VAT refund ───────────────────────────────────────────
export function calcVATRefund(countryCode, purchaseAmount) {
  const c = VAT_COUNTRIES[countryCode];
  if (!c || !c.hasRefund) return null;
  const embedded    = purchaseAmount * c.vatRate / (1 + c.vatRate);
  const fee         = embedded * (1 - c.netRefundFraction);
  const netRefund   = embedded * c.netRefundFraction;
  const belowMin    = purchaseAmount < c.minPurchase;
  const refundPct   = purchaseAmount > 0 ? netRefund / purchaseAmount : 0;
  return { embedded, fee, netRefund, refundPct, belowMin, minPurchase: c.minPurchase };
}
